#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


RE_INCLUDE = re.compile(r"^\s*(include|use)\s*<([^>]+)>\s*;?\s*$")


@dataclass(frozen=True)
class Variant:
    name: str
    source_scad: Path
    output_scad: Path


REPO_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_VARIANTS: list[Variant] = [
    Variant(
        name="gridfinity-cylinder-holder",
        source_scad=Path("scad_src/variants/gridfinity-cylinder-holder.scad"),
        output_scad=Path("gridfinity-cylinder-holder.scad"),
    ),
    Variant(
        name="gridfinity-rect-pocket-tray",
        source_scad=Path("scad_src/variants/gridfinity-rect-pocket-tray.scad"),
        output_scad=Path("gridfinity-rect-pocket-tray.scad"),
    ),
]


def _rel(p: Path) -> str:
    try:
        return str(p.resolve().relative_to(REPO_ROOT))
    except Exception:
        return str(p)


def _inline_scad(*, path: Path, seen: set[Path]) -> str:
    path = path.resolve()
    if path in seen:
        return f"// (skipped duplicate include) {_rel(path)}\n"
    seen.add(path)

    text = path.read_text(encoding="utf-8")
    out: list[str] = []
    out.append(f"// ===== BEGIN {_rel(path)} =====\n")

    for raw_line in text.splitlines(keepends=True):
        m = RE_INCLUDE.match(raw_line)
        if not m:
            out.append(raw_line)
            continue

        inc_raw = m.group(2).strip()
        inc_path = (path.parent / inc_raw).resolve()
        if not inc_path.exists():
            raise FileNotFoundError(f"Missing include: {inc_raw} (from {_rel(path)})")

        out.append(_inline_scad(path=inc_path, seen=seen))

    out.append(f"\n// ===== END {_rel(path)} =====\n")
    return "".join(out)


def build_variant(*, variant: Variant, output_dir: Path) -> tuple[Path, str]:
    src = (REPO_ROOT / variant.source_scad).resolve()
    if not src.exists():
        raise FileNotFoundError(f"Variant source not found: {_rel(src)}")

    header = (
        "/*\n"
        " * GENERATED FILE — DO NOT EDIT.\n"
        " *\n"
        f" * Source: {_rel(src)}\n"
        " *\n"
        " * This is a self-contained .scad intended for MakerWorld (no includes).\n"
        " * Generated by tools/build_makerworld_variants.py\n"
        " */\n\n"
    )

    body = _inline_scad(path=src, seen=set())
    content = header + body

    out_path = (output_dir / variant.output_scad).resolve()
    return out_path, content


def main() -> int:
    parser = argparse.ArgumentParser(description="Build self-contained MakerWorld-ready .scad files.")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=REPO_ROOT,
        help="Directory to write built .scad files into (default: repo root).",
    )
    parser.add_argument(
        "--variant",
        action="append",
        default=[],
        help="Variant name to build (can be repeated). If omitted, builds all variants.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write files; exit non-zero if outputs differ from expected.",
    )

    args = parser.parse_args()
    output_dir: Path = args.output_dir
    want: set[str] = set(args.variant or [])

    variants = [v for v in DEFAULT_VARIANTS if not want or v.name in want]
    missing = want - {v.name for v in variants}
    if missing:
        print(f"Unknown --variant: {', '.join(sorted(missing))}", file=sys.stderr)
        return 2

    output_dir.mkdir(parents=True, exist_ok=True)

    ok = True
    for v in variants:
        out_path, content = build_variant(variant=v, output_dir=output_dir)
        if args.check:
            existing = out_path.read_text(encoding="utf-8") if out_path.exists() else None
            if existing != content:
                print(f"OUT OF DATE: {_rel(out_path)}", file=sys.stderr)
                ok = False
            continue

        out_path.write_text(content, encoding="utf-8")
        print(f"WROTE: {_rel(out_path)}")

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())

